<template>
    <div id="app">
        <button @click="generateKillerIpsum()">
            Generate die wollah ipsum!
        </button>
        <p>{{ killerIpsum }}</p>
    </div>
</template>

<script>
    import _ from 'lodash';

    export default {
        name: 'app',
        data () {
            return {
                killerIpsum: '',
                killerPhrases: [
                    'AMG\'tje gehuurd? Weeejooow!',
                    'Al die kanker shit is nep',
                    'Alles draait om saaf, we zijn slaaf van die saaf',
                    'Alles draait om saaf, we zijn slaaf...',
                    'Alles wat je wil is rijk zijn',
                    'Dan doe iets met je leven voor je gaat maat',
                    'Dat is toch treurig, ik zeg het nog keurig',
                    'Dat waren mooie tijden, ja toch sahbi',
                    'De hele mannetje in je wijk zijn',
                    'Deze land wordt minder vol want ik ben challas binnenkort',
                    'Dolce & Gabbana',
                    'Effe naar de kapper geen schaamhaar daar',
                    'Elke avond liet ze mij haar kontgat zien',
                    'Elke dag op cheese net een kaasschaaf',
                    'En een domme kech die je zaad vraagt',
                    'En een piccatje voor instagram',
                    'En je moeder elke dag je kamer schoonmaakt?!',
                    'En meteen daarna winkelen bij Prada',
                    'En thuis zit je met een lege maag te kijken naar "24 Cooking"',
                    'Ewa broeder, laat maar',
                    'Ewa effe tranqir, ik was allang hier',
                    'Ewa lik m\'n qlaqel en eet m\'n pudding',
                    'Ewa, als je mij wil volgen, volg je moeder...',
                    'Ewa, ik pleeg aanslag op de kutje van je moeder',
                    'Ewaaaaa, Kamal heeft geen Instagram',
                    'Flashen met je geld, phel blaaskaak',
                    'Fock je Instagram, jij leeft in je scherm, dat is niks voor mij. Fock dat!',
                    'Geen Instagram, maar Interpol',
                    'Geen brood op de plank dus je klaagt vaak',
                    'Gratis tanken, wat een vieze kahbatron',
                    'Haar tabon altijd open net een tankstation',
                    'Hangen in de VIP met een batra',
                    'Hele dagen op Internet, waar is jouw leven?',
                    'Hele dure waggie want die rijdt fijn',
                    'Het is voor jou een noodzaak',
                    'IS staat voor ik steek m\'n zebi in je tegna, echt waar',
                    'Iba3esh heeft welloe gunning',
                    'Ik ben Killer Kamal en ze willen hebben dat ik meer ga rappen',
                    'Ik ben een Lijpe Boef, die z\'n money stackt',
                    'Ik ben een nachtdier , das de enige manier',
                    'Ik ben op papier, wahed bankier',
                    'Ik ga IS op je kehba',
                    'Ik heb geen Facebook',
                    'Ik heb geen Instagram',
                    'Ik heb geen Snapchat',
                    'Ik heb gehoord jouw moeder houdt van tinderen',
                    'Ik hoor je weer zeuren, dat opent geen deuren',
                    'Ik neuk hem de moeder, ik spuit in z\'n chapsel van die vieze kankerloeder',
                    'Ik pak je aan en dan moet je naar de fysio',
                    'Ik stuur je wel de tape als je wordt 18',
                    'Ik zag je laatst saaf lenen bij je arme mama',
                    'Ik zei het al: van je moeder maak ik video\s',
                    'Je bent een saaf slaaf',
                    'Je bent een saaf slaaf',
                    'Je draagt dure merk en die meid kijkt',
                    'Je eet alleen maar kutje, broeder, faka met jou, let op je voeding',
                    'Je hebt een heleboel sjans, maar een lege koelkast',
                    'Je hebt een nieuwe Rolex? Wauw!',
                    'Je krijgt een beetje toeslag (nou nou), ze3ma je leeft er goed van, schooier.',
                    'Je moeder op m\'n pik, dat is nostalgie',
                    'Je moet dit beseffen, ik word miljonair terwijl jij bitches beft',
                    'Je vindt het niet zo leuk dat ik het aankaart',
                    'Je volgt gewoon een Killer fan',
                    'Je wil een waggie met een dak, panorama',
                    'Je wil saaf saaf saaf saaf saaf saaf saaf saaf',
                    'Je ziet eruit alsof je naar een gala gaat',
                    'Je ziet ons in de nachtmerries van die blonde vent',
                    'Jij bent een handicap, doet alles voor die teven',
                    'Kalashnikov, krakaka in die tabon',
                    'Kameraad, waarom doe je als een vieze Jood?',
                    'Kan het niet begrijpen dat je alles doet voor sletten en pussy',
                    'Kanker gezeik wollah',
                    'Kanker hoerenzonen',
                    'Kontneuken is de insteek',
                    'Lieve help, wat een drama',
                    'Louis V bagga',
                    'Maar dat laat je koud, Himalaya',
                    'Maar de straat praat en is heet, phel lava',
                    'Maar een planga van Cartier is betaalbaar?!',
                    'Nieuwe Loubou\'s? Wahahauw!',
                    'Noem me Testosteronnie Flex',
                    'Nu ben je ze3ma baas',
                    'Om je moeder rust te geven hier in deze land',
                    'Om te shoppen in de P.C. Hooftstraat',
                    'Omdat je betaalt haar',
                    'Opgeladen ballen, ik heb moeilijk hoge libido',
                    'Outjes van Louis, Gucci en Balmain? Wahahauw!',
                    'Overdag duik ik onder als een vampier',
                    'Overdag duik ik onder als een vampier',
                    'Raap je kleine ballen bij elkaar en neem je kans',
                    'Rij in een merrie op de linkerbaan en we blazen 3André Hazes',
                    'Saaf is alles wat ik wil in deze leven, net een Lihoudi',
                    'Shab Woensel, we zijn niet onbekend',
                    'Spuiten en slikken, Geraldine Kemper, Geraldine Kamal',
                    'Terwijl je al maanden in het rood staat',
                    'Terwijl jij instagramt ben ik in het veld en maak dikke stacks saaf!',
                    'Thallaaaaa',
                    'Veel te eigenwijs, ewa ja',
                    'Voor m\'n werk heb ik nog geen vergunning',
                    'Waar je op kan spugen als een lama',
                    'Wahed pissebed',
                    'Want daar ben ik, la3youn',
                    'Want ik ben geen bezem',
                    'Want ik weet ze wil me aandacht',
                    'Want je kan niet altijd blijven leven zoals Peter Pan',
                    'Wees een man',
                    'Woensel is de Basis, iedereen weet wie de fock de baas is',
                    'Wollah kom me pijpen',
                    'Ze wil dat ik hem insteek, in d\'r windstreek',
                    'Ze wil niet minderen, das fucked up voor haar kinderen. Kanker zielig wollah',
                    'Ze zoeken naar m\'n winterhol',
                    'Zeg wollah, in m\'n broek zit \'n kanon',
                    'Zonder dat je god alleen om saaf en materiaal vraagt'
                ],
            }
        },
        methods: {
            generateKillerIpsum() {
                this.killerIpsum = _.shuffle(this.killerPhrases).join(', ').toString();
            }
        }
    }
</script>
