<template>
    <div id="app">
        <button @click="generateKillerIpsum()">
            Generate die wollah ipsum!
        </button>
        <p>{{ killerIpsum }}</p>
    </div>
</template>

<script>
    import _ from 'lodash';

    export default {
        name: 'app',
        data () {
            return {
                killerIpsum: '',
                killerPhrases: [
                    'Kanker hoerenzonen',
                    'Kanker gezeik wollah',
                    'Ik heb geen Instagram',
                    'Ik heb geen Facebook',
                    'Ik heb geen Snapchat',
                    'Want ik ben geen bezem',
                    'Hele dagen op Internet, waar is jouw leven?',
                    'Jij bent een handicap, doet alles voor die teven',
                    'Ik heb geen Instagram',
                    'Ik heb geen Facebook',
                    'Ik heb geen Snapchat',
                    'Want ik ben geen bezem',
                    'Hele dagen op Internet, waar is jouw leven?',
                    'Jij bent een handicap, doet alles voor die teven',
                    'Ewaaaaa, Kamal heeft geen Instagram',
                    'Al die kanker shit is nep',
                    'Je volgt gewoon een Killer fan',
                    'Geen Instagram, maar Interpol',
                    'Ze zoeken naar m\'n winterhol',
                    'Deze land wordt minder vol want ik ben challas binnenkort',
                    'Thallaaaaa',
                    'Saaf is alles wat ik wil in deze leven, net een Lihoudi',
                    'Kan het niet begrijpen dat je alles doet voor sletten en pussy',
                    'Je eet alleen maar kutje, broeder, faka met jou, let op je voeding',
                    'En thuis zit je met een lege maag te kijken naar "24 Cooking"',
                    'Dat is toch treurig, ik zeg het nog keurig',
                    'Ik hoor je weer zeuren, dat opent geen deuren',
                    'Je hebt een heleboel sjans, maar een lege koelkast',
                    'Je krijgt een beetje toeslag (nou nou), ze3ma je leeft er goed van, schooier.',
                    'Fock je Instagram, jij leeft in je scherm, dat is niks voor mij. Fock dat!',
                    'Terwijl jij instagramt ben ik in het veld en maak dikke stacks saaf!',
                    'Ik ben Killer Kamal en ze willen hebben dat ik meer ga rappen',
                    'Je moet dit beseffen, ik word miljonair terwijl jij bitches beft',
                    'Wahed pissebed',
                    'Ik heb gehoord jouw moeder houdt van tinderen',
                    'Ze wil niet minderen, das fucked up voor haar kinderen. Kanker zielig wollah',
                    'Haar tabon altijd open net een tankstation',
                    'Gratis tanken, wat een vieze kahbatron',
                    'Je moeder op m\'n pik, dat is nostalgie',
                    'Elke avond liet ze mij haar kontgat zien',
                    'Ik stuur je wel de tape als je wordt 18',
                    'Dat waren mooie tijden, ja toch sahbi',
                    'Kameraad, waarom doe je als een vieze Jood?',
                    'Ik pak je aan en dan moet je naar de fysio',
                    'Ik zei het al: van je moeder maak ik video\s',
                    'Opgeladen ballen, ik heb moeilijk hoge libido',
                    'Ewa effe tranqir, ik was allang hier',
                    'Ik ben op papier, wahed bankier',
                    'Ik ben een nachtdier , das de enige manier',
                    'Overdag duik ik onder als een vampier',
                    'Overdag duik ik onder als een vampier',
                    'Woensel is de Basis, iedereen weet wie de fock de baas is',
                    'Rij in een merrie op de linkerbaan en we blazen 3André Hazes',
                    'Voor m\'n werk heb ik nog geen vergunning',
                    'Iba3esh heeft welloe gunning',
                    'Ewa lik m\'n qlaqel en eet m\'n pudding',
                    'Ik heb geen Instagram',
                    'Ik heb geen Facebook',
                    'Ik heb geen Snapchat',
                    'Want ik ben geen bezem',
                    'Hele dagen op Internet, waar is jouw leven?',
                    'Jij bent een handicap, doet alles voor die teven',
                    'Ik heb geen Instagram',
                    'Ik heb geen Facebook',
                    'Ik heb geen Snapchat',
                    'Want ik ben geen bezem',
                    'Hele dagen op Internet, waar is jouw leven?',
                    'Jij bent een handicap, doet alles voor die teven',
                    'Ewa, als je mij wil volgen, volg je moeder...',
                    'Want daar ben ik, la3youn',
                    'Ewa, ik pleeg aanslag op de kutje van je moeder',
                    'Want ik weet ze wil me aandacht',
                    'Ze wil dat ik hem insteek, in d\'r windstreek',
                    'Kontneuken is de insteek',
                    'Ik ga IS op je kehba',
                    'IS staat voor ik steek m\'n zebi in je tegna, echt waar',
                    'Zeg wollah, in m\'n broek zit \'n kanon',
                    'Kalashnikov, krakaka in die tabon',
                    'Noem me Testosteronnie Flex',
                    'Ik ben een Lijpe Boef, die z\'n money stackt',
                    'Shab Woensel, we zijn niet onbekend',
                    'Je ziet ons in de nachtmerries van die blonde vent',
                    'Ik neuk hem de moeder, ik spuit in z\'n chapsel van die vieze kankerloeder',
                    'Spuiten en slikken, Geraldine Kemper, Geraldine Kamal',
                    'Wollah kom me pijpen',
                    'Je hebt een nieuwe Rolex? Wauw!',
                    'Nieuwe Loubou\'s? Wahahauw!',
                    'AMG\'tje gehuurd? Weeejooow!',
                    'Outjes van Louis, Gucci en Balmain? Wahahauw!',
                    'Alles wat je wil is rijk zijn',
                    'De hele mannetje in je wijk zijn',
                    'Hele dure waggie want die rijdt fijn',
                    'Je draagt dure merk en die meid kijkt',
                    'Je wil saaf saaf saaf saaf saaf saaf saaf saaf',
                    'Alles draait om saaf, we zijn slaaf van die saaf',
                    'Je bent een saaf slaaf',
                    'Elke dag op cheese net een kaasschaaf',
                    'Geen brood op de plank dus je klaagt vaak',
                    'Maar een planga van Cartier is betaalbaar?!',
                    'Lieve help, wat een drama',
                    'Ik zag je laatst saaf lenen bij je arme mama',
                    'En meteen daarna winkelen bij Prada',
                    'Dolce & Gabbana',
                    'Louis V bagga',
                    'Nu ben je ze3ma baas',
                    'Je ziet eruit alsof je naar een gala gaat',
                    'Effe naar de kapper geen schaamhaar daar',
                    'En een piccatje voor instagram',
                    'Flashen met je geld, phel blaaskaak',
                    'Maar de straat praat en is heet, phel lava',
                    'Maar dat laat je koud, Himalaya',
                    'Veel te eigenwijs, ewa ja',
                    'Alles wat je wil is rijk zijn',
                    'De hele mannetje in je wijk zijn',
                    'Hele dure waggie want die rijdt fijn',
                    'Je draagt dure merk en die meid kijkt',
                    'Je wil saaf saaf saaf saaf saaf saaf saaf saaf',
                    'Alles draait om saaf, we zijn slaaf...',
                    'Alles wat je wil is rijk zijn',
                    'De hele mannetje in je wijk zijn',
                    'Hele dure waggie want die rijdt fijn',
                    'Je draagt dure merk en die meid kijkt',
                    'Je wil saaf saaf saaf saaf saaf saaf saaf saaf',
                    'Alles draait om saaf, we zijn slaaf van die saaf',
                    'Je bent een saaf slaaf',
                    'Je vindt het niet zo leuk dat ik het aankaart',
                    'Dan doe iets met je leven voor je gaat maat',
                    'Zonder dat je god alleen om saaf en materiaal vraagt',
                    'Je wil een waggie met een dak, panorama',
                    'Hangen in de VIP met een batra',
                    'En een domme kech die je zaad vraagt',
                    'Waar je op kan spugen als een lama',
                    'Omdat je betaalt haar',
                    'Ewa broeder, laat maar',
                    'Het is voor jou een noodzaak',
                    'Om te shoppen in de P.C. Hooftstraat',
                    'Terwijl je al maanden in het rood staat',
                    'En je moeder elke dag je kamer schoonmaakt?!',
                    'Wees een man',
                    'Raap je kleine ballen bij elkaar en neem je kans',
                    'Om je moeder rust te geven hier in deze land',
                    'Want je kan niet altijd blijven leven zoals Peter Pan',
                    'Alles wat je wil is rijk zijn',
                    'De hele mannetje in je wijk zijn',
                    'Hele dure waggie want die rijdt fijn',
                    'Je draagt dure merk en die meid kijkt',
                    'Je wil saaf saaf saaf saaf saaf saaf saaf saaf',
                    'Alles draait om saaf, we zijn slaaf',
                    'Alles wat je wil is rijk zijn',
                    'De hele mannetje in je wijk zijn',
                    'Hele dure waggie want die rijdt fijn',
                    'Je draagt dure merk en die meid kijkt',
                    'Je wil saaf saaf saaf saaf saaf saaf saaf saaf',
                    'Alles draait om saaf, we zijn slaaf van die saaf'
                ],
            }
        },
        methods: {
            generateKillerIpsum() {
                this.killerIpsum = _.shuffle(this.killerPhrases).join(', ').toString();
            }
        }
    }
</script>
